# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---


################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/istc.com/msp

    - &TeaMaster
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: TeaMasterMSP

        # ID to load the MSP definition as
        ID: TeaMasterMSP

        MSPDir: crypto-config/peerOrganizations/teamaster.istc.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.teamaster.istc.com
              Port: 7051
    - &ISTC
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ISTCMSP

        # ID to load the MSP definition as
        ID: ISTCMSP

        MSPDir: crypto-config/peerOrganizations/istc.istc.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.istc.istc.com
              Port: 7051
    - &Wholesaler
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: WholesalerMSP

        # ID to load the MSP definition as
        ID: WholesalerMSP

        MSPDir: crypto-config/peerOrganizations/wholesaler.istc.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.wholesaler.istc.com
              Port: 7051
    - &TeaTaster
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: TeaTasterMSP

        # ID to load the MSP definition as
        ID: TeaTasterMSP

        MSPDir: crypto-config/peerOrganizations/teataster.istc.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.teataster.istc.com
              Port: 7051
    - &Lab
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: LabMSP

        # ID to load the MSP definition as
        ID: LabMSP

        MSPDir: crypto-config/peerOrganizations/lab.istc.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.lab.istc.com
              Port: 7051
    - &TeaBoardOfIndia
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: TeaBoardOfIndiaMSP

        # ID to load the MSP definition as
        ID: TeaBoardOfIndiaMSP

        MSPDir: crypto-config/peerOrganizations/teaboardofindia.istc.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.teaboardofindia.istc.com
              Port: 7051




################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.istc.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

###############################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    ISTCOrgOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            ISTConsortium:
                Organizations:
                    - *TeaMaster
                    - *ISTC
                    - *Wholesaler
                    - *TeaTaster
                    - *Lab
                    - *TeaBoardOfIndia

    ISTCOrgChannel:
        Consortium: ISTConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *TeaMaster
                - *ISTC
                - *Wholesaler
                - *TeaTaster
                - *Lab
                - *TeaBoardOfIndia
