--- # ---------------------------------------------------------------------------
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: istc.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # TeaMaster
  # ---------------------------------------------------------------------------
  - Name: TeaMaster
    Domain: teamaster.istc.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # ISTC platform owner
  # ---------------------------------------------------------------------------
  - Name: ISTC
    Domain: istc.istc.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Wholesaler
  # ---------------------------------------------------------------------------
  - Name: Wholesaler
    Domain: wholesaler.istc.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # TeaTaster
  # ---------------------------------------------------------------------------
  - Name: TeaTaster
    Domain: teataster.istc.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Lab
  # ---------------------------------------------------------------------------
  - Name: Lab
    Domain: lab.istc.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # TeaBoardOfIndia
  # ---------------------------------------------------------------------------
  - Name: TeaBoardOfIndia
    Domain: teaboardofindia.istc.com
    Template:
      Count: 1
    Users:
      Count: 1



